version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports: 
      - "80:80"
    networks:
      - internal
    volumes:
      - ./www/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    networks:
      - internal
    volumes:
      - ./www/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    
networks:
  internal:
    driver: bridge
